// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// Colour glyphs from MaulColor.ttf (generated by make_color_font.py): its
// A, at an em of 10 pixels, is a box from 1 to 9 across and 0 to 8 up of
// palette entry 0, its right half (5 to 9) of entry 1 over it, and a box
// from 3 to 5 across and 2 to 4 up of the text's colour; palette 0 is
// opaque red and half transparent blue, palette 1 green and yellow. Its
// B has no colour layers.

#include "test_harness.h"

#include "maul-ui/font.h"
#include "maul-ui/glyph_image.h"
#include "maul-ui/text_block.h"

#include <string.h>

#include "color.inc"

enum
{
    GLYPH_A = 1,
    GLYPH_B = 2
};

static unsigned char s_pixels[4096];

typedef struct Scene
{
    muiTextService* service;
    uint64_t font;
} Scene;

static Scene MakeScene(void)
{
    Scene scene = {0};
    muiTextServiceDef def = muiDefaultTextServiceDef();
    CHECK(muiCreateTextService(&def, &scene.service) == mui_success, "a text service");
    muiFontDef font = muiDefaultFontDef();
    font.data = s_color;
    font.size = sizeof s_color;
    font.dataMode = mui_fontDataBorrow;
    muiFontId id = {0, 0};
    CHECK(muiCreateFont(scene.service, &font, &id) == mui_success, "Maul Color");
    scene.font = muiFont_GetKey(id);
    return scene;
}

// Whether the pixel at x, y (y up, from the image's place) is these bytes.
static bool Is(const muiGlyphImage* image, int32_t x, int32_t y, int r, int g, int b, int a)
{
    uint32_t column = (uint32_t)(x - image->left);
    uint32_t row = (uint32_t)(image->top - 1 - y);
    const unsigned char* p = &s_pixels[((size_t)row * image->width + column) * 4];
    return p[0] == r && p[1] == g && p[2] == b && p[3] == a;
}

static void TestLayers(void)
{
    Scene scene = MakeScene();
    const muiLinearColor green = {0.0f, 1.0f, 0.0f, 1.0f};
    muiGlyphImage image = {0};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              image.left == 1 && image.top == 8 && image.width == 8 && image.height == 8,
          "the layers' joint box");
    // Blue at alpha 128 over red: linear 0.498 red and 0.502 blue, 187
    // and 188 encoded.
    CHECK(Is(&image, 1, 7, 255, 0, 0, 255) && Is(&image, 4, 0, 255, 0, 0, 255), "palette entry 0");
    CHECK(Is(&image, 5, 7, 187, 0, 188, 255) && Is(&image, 8, 0, 187, 0, 188, 255),
          "entry 1, half transparent, over it");
    CHECK(Is(&image, 3, 2, 0, 255, 0, 255) && Is(&image, 4, 3, 0, 255, 0, 255) &&
              Is(&image, 2, 2, 255, 0, 0, 255),
          "the text's colour");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 1, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              Is(&image, 1, 7, 0, 255, 0, 255) && Is(&image, 8, 0, 255, 255, 0, 255),
          "the second palette");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 7, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              Is(&image, 1, 7, 255, 0, 0, 255),
          "a palette past the font's, the first");
    const muiLinearColor clear = {0.0f, 0.0f, 0.0f, 0.0f};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, clear, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              Is(&image, 3, 2, 255, 0, 0, 255),
          "a clear text colour shows what is under it");
    // Half a pixel right: the joint box widens by one, its first column
    // half covered by red.
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.5f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              image.left == 1 && image.width == 9 && Is(&image, 1, 7, 188, 0, 0, 128),
          "an offset pen");
    image = (muiGlyphImage){5, 5, 5, 5};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_B, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_empty &&
              image.width == 0 && image.height == 0,
          "a glyph without colour is empty");
    muiDestroyTextService(scene.service);
}

static void TestContract(void)
{
    Scene scene = MakeScene();
    const muiLinearColor green = {0.0f, 1.0f, 0.0f, 1.0f};
    muiGlyphImage image = {0};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                              NULL, 0) == mui_errorCapacity &&
              image.width == 8 && image.height == 8,
          "too few bytes, the size told");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, 8 * 8 * 4 - 1) == mui_errorCapacity &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                                  s_pixels, 8 * 8 * 4) == mui_success,
          "four bytes a pixel");
    CHECK(muiRenderColorGlyph(NULL, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image, s_pixels,
                              sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, NULL,
                                  s_pixels, sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                                  NULL, 4) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 0.0f, 0.0f, 0, green, &image,
                                  s_pixels, sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 1.0f, 0, green, &image,
                                  s_pixels, sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, 100, 10.0f, 0.0f, 0, green, &image,
                                  s_pixels, sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font + 1, GLYPH_A, 10.0f, 0.0f, 0, green,
                                  &image, s_pixels, sizeof s_pixels) == mui_errorStale,
          "outside the contract");
    muiDestroyTextService(scene.service);
}

int main(void)
{
    TestLayers();
    TestContract();
    return s_failures == 0 ? 0 : 1;
}
