// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// Colour bitmap glyphs from MaulBitmap.ttf (generated by
// make_bitmap_font.py, which describes its glyphs): a font without
// outlines, every CBLC index format and CBDT image format, two strikes.
// Glyphs drawn at their strike's size match its pixels; others are
// scaled, the strike chosen as the smallest reaching the size. Then the
// font damaged at random, its glyphs drawn or refused without harm under
// the sanitizers; the seed is fixed, so a failure repeats.

#include "test_harness.h"

#include "maul-ui/font.h"
#include "maul-ui/glyph_image.h"
#include "maul-ui/text_block.h"

#include <string.h>

#include "bitmap.inc"

enum
{
    GLYPHS = 14,
    DAMAGE_ROUNDS = 400
};

static unsigned char s_pixels[1 << 16];
static unsigned char s_font[sizeof s_bitmap];

typedef struct Scene
{
    muiTextService* service;
    uint64_t font;
} Scene;

static bool MakeScene(Scene* scene, const unsigned char* data, size_t size)
{
    *scene = (Scene){0};
    muiTextServiceDef def = muiDefaultTextServiceDef();
    muiFontDef font = muiDefaultFontDef();
    font.data = data;
    font.size = size;
    font.dataMode = mui_fontDataBorrow;
    muiFontId id = {0, 0};
    if (muiCreateTextService(&def, &scene->service) != mui_success ||
        muiCreateFont(scene->service, &font, &id) != mui_success)
    {
        return false;
    }
    scene->font = muiFont_GetKey(id);
    return true;
}

static muiResult Draw(const Scene* scene, uint32_t glyph, float size, float offset,
                      muiGlyphImage* image)
{
    const muiLinearColor green = {0.0f, 1.0f, 0.0f, 1.0f};
    return muiRenderColorGlyph(scene->service, scene->font, glyph, size, offset, 0, green, image,
                               s_pixels, sizeof s_pixels);
}

// Whether a glyph draws at a size into this box, left and top, width and
// height.
static bool BoxIs(const Scene* scene, uint32_t glyph, float size, float offset, int32_t left,
                  int32_t top, uint32_t width, uint32_t height, muiGlyphImage* image)
{
    return Draw(scene, glyph, size, offset, image) == mui_success && image->left == left &&
           image->top == top && image->width == width && image->height == height;
}

// Whether the pixel at x, y (y up, from the image's place) is these bytes.
static bool Is(const muiGlyphImage* image, int32_t x, int32_t y, int r, int g, int b, int a)
{
    uint32_t column = (uint32_t)(x - image->left);
    uint32_t row = (uint32_t)(image->top - 1 - y);
    const unsigned char* p = &s_pixels[((size_t)row * image->width + column) * 4];
    return p[0] == r && p[1] == g && p[2] == b && p[3] == a;
}

static void TestFormats(void)
{
    Scene scene;
    CHECK(MakeScene(&scene, s_bitmap, sizeof s_bitmap), "a font of bitmaps alone");
    muiGlyphImage image = {0};
    CHECK(BoxIs(&scene, 1, 10.0f, 0.0f, 1, 8, 8, 8, &image) && Is(&image, 1, 7, 255, 0, 0, 255) &&
              Is(&image, 5, 0, 0, 0, 255, 255),
          "index format 1, image format 17");
    CHECK(BoxIs(&scene, 2, 10.0f, 0.0f, 3, 5, 2, 2, &image) && Is(&image, 4, 3, 0, 255, 0, 255),
          "the next glyph of the range");
    CHECK(BoxIs(&scene, 3, 10.0f, 0.0f, 2, 4, 2, 2, &image) && Is(&image, 2, 2, 0, 0, 255, 255),
          "index format 3, image format 18");
    CHECK(BoxIs(&scene, 4, 10.0f, 0.0f, 1, 3, 2, 2, &image) && Is(&image, 1, 1, 255, 0, 0, 255) &&
              BoxIs(&scene, 5, 10.0f, 0.0f, 1, 3, 2, 2, &image) && Is(&image, 1, 1, 0, 255, 0, 255),
          "index format 2, image format 19");
    CHECK(BoxIs(&scene, 6, 10.0f, 0.0f, 0, 2, 2, 2, &image) && Is(&image, 0, 0, 0, 0, 255, 255) &&
              BoxIs(&scene, 8, 10.0f, 0.0f, 0, 2, 2, 2, &image) &&
              Is(&image, 0, 0, 255, 0, 0, 255) && Draw(&scene, 7, 10.0f, 0.0f, &image) == mui_empty,
          "index format 4, a glyph of its range without an image");
    CHECK(BoxIs(&scene, 9, 10.0f, 0.0f, 2, 2, 2, 2, &image) && Is(&image, 2, 0, 0, 255, 0, 255) &&
              BoxIs(&scene, 11, 10.0f, 0.0f, 2, 2, 2, 2, &image) &&
              Is(&image, 2, 0, 0, 0, 255, 255) &&
              Draw(&scene, 10, 10.0f, 0.0f, &image) == mui_empty,
          "index format 5, a glyph of its range without an image");
    CHECK(Draw(&scene, 13, 10.0f, 0.0f, &image) == mui_empty && image.width == 0,
          "a glyph without a bitmap is empty");
    CHECK(muiRenderGlyph(scene.service, scene.font, 1, 10.0f, 0.0f, &image, s_pixels,
                         sizeof s_pixels) == mui_success &&
              image.width == 0,
          "no coverage in a font without outlines");
    muiDestroyTextService(scene.service);
}

static void TestScaling(void)
{
    Scene scene;
    CHECK(MakeScene(&scene, s_bitmap, sizeof s_bitmap), "the font");
    muiGlyphImage image = {0};
    // 20 ppem's glyph 1 is green on its right, 10 ppem's blue.
    CHECK(BoxIs(&scene, 1, 20.0f, 0.0f, 2, 16, 16, 16, &image) && Is(&image, 12, 8, 0, 255, 0, 255),
          "the strike of the size itself");
    CHECK(BoxIs(&scene, 1, 15.0f, 0.0f, 1, 12, 13, 12, &image) &&
              Is(&image, 10, 6, 0, 255, 0, 255) && Is(&image, 3, 6, 255, 0, 0, 255),
          "the smallest strike reaching the size, shrunk");
    CHECK(Draw(&scene, 1, 5.0f, 0.0f, &image) == mui_success && Is(&image, 3, 1, 0, 0, 255, 255),
          "the smallest strike of all for a smaller size");
    CHECK(Draw(&scene, 1, 30.0f, 0.0f, &image) == mui_success && image.width == 24 &&
              Is(&image, 20, 10, 0, 255, 0, 255),
          "the largest strike, grown, for a larger size");
    // Glyph 12 is only in the 20 ppem strike: its top row of four red,
    // halved, makes a top row half red.
    CHECK(BoxIs(&scene, 12, 10.0f, 0.0f, 0, 2, 2, 2, &image) && Is(&image, 0, 1, 188, 0, 0, 128) &&
              Is(&image, 1, 0, 0, 0, 0, 0),
          "a strike without the glyph passed over, the image averaged");
    // Half a pixel right: the first column half red.
    CHECK(BoxIs(&scene, 1, 10.0f, 0.5f, 1, 8, 9, 8, &image) && Is(&image, 1, 7, 188, 0, 0, 128) &&
              Is(&image, 2, 7, 255, 0, 0, 255),
          "an offset pen");
    muiDestroyTextService(scene.service);
}

static uint32_t Next(uint32_t* state)
{
    *state ^= *state << 13;
    *state ^= *state >> 17;
    *state ^= *state << 5;
    return *state;
}

static void TestDamage(void)
{
    uint32_t state = 0x2545F491u;
    uint32_t made = 0;
    for (uint32_t round = 0; round < DAMAGE_ROUNDS; round++)
    {
        memcpy(s_font, s_bitmap, sizeof s_bitmap);
        uint32_t flips = 1 + Next(&state) % 8;
        for (uint32_t i = 0; i < flips; i++)
        {
            s_font[Next(&state) % sizeof s_font] ^= (unsigned char)(1u << (Next(&state) % 8));
        }
        Scene scene;
        if (MakeScene(&scene, s_font, sizeof s_font))
        {
            made++;
            for (uint32_t glyph = 0; glyph < GLYPHS; glyph++)
            {
                muiGlyphImage image = {0};
                (void)Draw(&scene, glyph, 7.0f + (float)(glyph % 4) * 6.0f, 0.25f, &image);
            }
        }
        muiDestroyTextService(scene.service);
    }
    CHECK(made > DAMAGE_ROUNDS / 4, "damaged fonts made and drawn or refused");
}

int main(void)
{
    TestFormats();
    TestScaling();
    TestDamage();
    return s_failures == 0 ? 0 : 1;
}
