// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// Colour glyphs from MaulColor.ttf (generated by make_color_font.py): its
// A, at an em of 10 pixels, is a layer with no outline, a box from 1 to 9
// across and 0 to 8 up of palette entry 0, its right half (5 to 9) of
// entry 1 over it, a box from 3 to 5 across and 2 to 4 up of the text's
// colour, and a box from 6 to 8 across and 2 to 4 up of entry 2, past
// the palettes' two; palette 0 is opaque red and half transparent blue,
// palette 1 green and yellow. Its B has no colour layers. Glyphs 10 on are
// version 1 paint graphs, one for each kind of paint, described in the
// font's script. Then the font damaged at random, half its flips in its
// COLR and CPAL tables, every glyph drawn or refused without harm under
// the sanitizers; the seed is fixed, so a failure repeats.

#include "test_harness.h"

#include "maul-ui/font.h"
#include "maul-ui/glyph_image.h"
#include "maul-ui/text_block.h"

#include <stdlib.h>
#include <string.h>

#include "color.inc"

enum
{
    GLYPH_A = 1,
    GLYPH_B = 2,
    LAYERED = 10,
    MOVED,
    TURNED,
    SCALED,
    SKEWED,
    TRANSFORMED,
    REUSED,
    CLIPPED,
    LOOPED,
    FLATTENED,
    NESTED,
    BOXED_LOOP,
    LINEAR_PAD,
    LINEAR_REPEAT,
    LINEAR_REFLECT,
    LINEAR_TURNED,
    RADIAL,
    RADIAL_TUBE,
    SWEEP,
    LINEAR_UNORDERED,
    RADIAL_TANGENT,
    LINEAR_SHEARED,
    LINEAR_HARD,
    COMPOSITED,
    BRANCHED,
    BOXED_BRANCHED = BRANCHED + 30
};

enum
{
    DAMAGE_ROUNDS = 1500
};

static unsigned char s_pixels[4096];
static unsigned char s_large[64 * 64 * 4];
static unsigned char s_damaged[sizeof s_color];
static unsigned char s_onePalette[sizeof s_color];

typedef struct Scene
{
    muiTextService* service;
    uint64_t font;
} Scene;

static Scene MakeScene(void)
{
    Scene scene = {0};
    muiTextServiceDef def = muiDefaultTextServiceDef();
    CHECK(muiCreateTextService(&def, &scene.service) == mui_success, "a text service");
    muiFontDef font = muiDefaultFontDef();
    font.data = s_color;
    font.size = sizeof s_color;
    font.dataMode = mui_fontDataBorrow;
    muiFontId id = {0, 0};
    CHECK(muiCreateFont(scene.service, &font, &id) == mui_success, "Maul Color");
    scene.font = muiFont_GetKey(id);
    return scene;
}

// Whether the pixel at x, y (y up, from the image's place) is these bytes.
static bool Is(const muiGlyphImage* image, int32_t x, int32_t y, int r, int g, int b, int a)
{
    uint32_t column = (uint32_t)(x - image->left);
    uint32_t row = (uint32_t)(image->top - 1 - y);
    const unsigned char* p = &s_pixels[((size_t)row * image->width + column) * 4];
    return p[0] == r && p[1] == g && p[2] == b && p[3] == a;
}

// Whether the pixel at x, y is opaque and red and green within 1 of
// these: a gradient's colour from red to green, mixed in linear light.
static bool Mixed(const muiGlyphImage* image, int32_t x, int32_t y, int r, int g)
{
    uint32_t column = (uint32_t)(x - image->left);
    uint32_t row = (uint32_t)(image->top - 1 - y);
    const unsigned char* p = &s_pixels[((size_t)row * image->width + column) * 4];
    return abs(p[0] - r) <= 1 && abs(p[1] - g) <= 1 && p[2] == 0 && p[3] == 255;
}

static void TestLayers(void)
{
    Scene scene = MakeScene();
    const muiLinearColor green = {0.0f, 1.0f, 0.0f, 1.0f};
    muiGlyphImage image = {0};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              image.left == 1 && image.top == 8 && image.width == 8 && image.height == 8,
          "the layers' joint box");
    // Blue at alpha 128 over red: linear 0.498 red and 0.502 blue, 187
    // and 188 encoded.
    CHECK(Is(&image, 1, 7, 255, 0, 0, 255) && Is(&image, 4, 0, 255, 0, 0, 255), "palette entry 0");
    CHECK(Is(&image, 5, 7, 187, 0, 188, 255) && Is(&image, 8, 0, 187, 0, 188, 255),
          "entry 1, half transparent, over it");
    CHECK(Is(&image, 7, 3, 187, 0, 188, 255), "an entry past the palette, transparent");
    CHECK(Is(&image, 3, 2, 0, 255, 0, 255) && Is(&image, 4, 3, 0, 255, 0, 255) &&
              Is(&image, 2, 2, 255, 0, 0, 255),
          "the text's colour");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 1, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              Is(&image, 1, 7, 0, 255, 0, 255) && Is(&image, 8, 0, 255, 255, 0, 255),
          "the second palette");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 7, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              Is(&image, 1, 7, 255, 0, 0, 255),
          "a palette past the font's, the first");
    const muiLinearColor clear = {0.0f, 0.0f, 0.0f, 0.0f};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, clear, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              Is(&image, 3, 2, 255, 0, 0, 255),
          "a clear text colour shows what is under it");
    // Half a pixel right: the joint box widens by one, its first column
    // half covered by red.
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.5f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              image.left == 1 && image.width == 9 && Is(&image, 1, 7, 188, 0, 0, 128),
          "an offset pen");
    unsigned char first[9 * 8 * 4];
    memcpy(first, s_pixels, sizeof first);
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.5f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              memcmp(first, s_pixels, sizeof first) == 0,
          "rendered again, the same");
    image = (muiGlyphImage){5, 5, 5, 5};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_B, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_empty &&
              image.width == 0 && image.height == 0,
          "a glyph without colour is empty");
    muiDestroyTextService(scene.service);
}

// Whether a glyph renders at an em of 10 and a pen offset into this box,
// left and top, width and height, in palette 0 and green text.
static bool BoxIs(Scene* scene, uint32_t glyph, float offset, int32_t left, int32_t top,
                  uint32_t width, uint32_t height, muiGlyphImage* image)
{
    const muiLinearColor green = {0.0f, 1.0f, 0.0f, 1.0f};
    return muiRenderColorGlyph(scene->service, scene->font, glyph, 10.0f, offset, 0, green, image,
                               s_pixels, sizeof s_pixels) == mui_success &&
           image->left == left && image->top == top && image->width == width &&
           image->height == height;
}

static void TestPaints(void)
{
    Scene scene = MakeScene();
    muiGlyphImage image = {0};
    // The text's colour at half alpha over red: linear half red and half
    // green, 188 encoded.
    CHECK(BoxIs(&scene, LAYERED, 0.0f, 1, 8, 8, 8, &image) && Is(&image, 1, 7, 255, 0, 0, 255) &&
              Is(&image, 3, 2, 188, 188, 0, 255) && Is(&image, 5, 2, 255, 0, 0, 255),
          "layers, a solid's alpha and the text's colour");
    const muiLinearColor green = {0.0f, 1.0f, 0.0f, 1.0f};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, LAYERED, 10.0f, 0.0f, 1, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              Is(&image, 1, 7, 0, 255, 0, 255),
          "a graph in the second palette");
    CHECK(BoxIs(&scene, MOVED, 0.0f, 6, 5, 2, 2, &image) && Is(&image, 6, 3, 255, 0, 0, 255) &&
              Is(&image, 7, 4, 255, 0, 0, 255),
          "a translation");
    CHECK(BoxIs(&scene, MOVED, 0.5f, 6, 5, 3, 2, &image) && Is(&image, 6, 3, 188, 0, 0, 128) &&
              Is(&image, 7, 3, 255, 0, 0, 255),
          "a translation at an offset pen");
    CHECK(BoxIs(&scene, TURNED, 0.0f, 2, 6, 1, 4, &image) && Is(&image, 2, 5, 255, 0, 0, 255),
          "a rotation counter-clockwise about a centre");
    CHECK(BoxIs(&scene, SCALED, 0.0f, 3, 3, 3, 1, &image) && Is(&image, 5, 2, 255, 0, 0, 255),
          "a scale about a centre");
    // At 3 to 4 up, the skewed dot spans 2 to 1 on its left and 4 to 3 on
    // its right: pixel 2, 3 is whole, pixel 4, 3 untouched.
    CHECK(BoxIs(&scene, SKEWED, 0.0f, 1, 4, 4, 2, &image) && Is(&image, 2, 3, 255, 0, 0, 255) &&
              Is(&image, 4, 3, 0, 0, 0, 0),
          "a skew, its top leaning left");
    CHECK(BoxIs(&scene, TRANSFORMED, 0.0f, 3, 4, 4, 2, &image) &&
              Is(&image, 5, 3, 255, 0, 0, 255) && Is(&image, 3, 3, 0, 0, 0, 0),
          "an affine transform");
    CHECK(BoxIs(&scene, REUSED, 0.0f, 3, 5, 2, 2, &image) && Is(&image, 3, 3, 255, 0, 0, 255),
          "another colour glyph's graph, transformed");
    // The clip box's lower row is half inside it.
    CHECK(BoxIs(&scene, CLIPPED, 0.0f, 3, 4, 2, 2, &image) && Is(&image, 3, 2, 188, 0, 0, 128) &&
              Is(&image, 4, 3, 255, 0, 0, 255),
          "a clip box");
    // A quarter of the corner pixel inside: linear red 0.25, 137 encoded.
    CHECK(BoxIs(&scene, CLIPPED, 0.5f, 3, 4, 3, 2, &image) && Is(&image, 3, 2, 137, 0, 0, 64) &&
              Is(&image, 4, 2, 188, 0, 0, 128) && Is(&image, 4, 3, 255, 0, 0, 255) &&
              Is(&image, 5, 3, 188, 0, 0, 128),
          "nothing outside the clip box, at an offset pen");
    CHECK(BoxIs(&scene, NESTED, 0.0f, 4, 3, 3, 1, &image) && Is(&image, 4, 2, 255, 0, 0, 255) &&
              Is(&image, 6, 2, 255, 0, 0, 255),
          "transforms nested, the outer applied last");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, LOOPED, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_errorFormat,
          "a graph that paints itself");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, BOXED_LOOP, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_errorFormat,
          "a graph that paints itself, in a clip box");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, FLATTENED, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_errorFormat,
          "a skew of a quarter turn, its outline without end");
    muiDestroyTextService(scene.service);
}

// Gradients over the whole box, 1 to 9 across and 0 to 8 up, red to the
// text's green; the expected bytes are the colours mixed in linear light
// at each pixel's centre, encoded.
static void TestGradients(void)
{
    Scene scene = MakeScene();
    muiGlyphImage image = {0};
    // From 3 to 5 across: pixel 1 at -0.75, pixel 4 at 0.75, pixel 7 at
    // 2.25.
    CHECK(BoxIs(&scene, LINEAR_PAD, 0.0f, 1, 8, 8, 8, &image) && Mixed(&image, 1, 4, 255, 0) &&
              Mixed(&image, 4, 4, 137, 225) && Mixed(&image, 7, 4, 0, 255) &&
              Mixed(&image, 4, 0, 137, 225),
          "a linear gradient, padded");
    CHECK(BoxIs(&scene, LINEAR_REPEAT, 0.0f, 1, 8, 8, 8, &image) && Mixed(&image, 1, 4, 225, 137) &&
              Mixed(&image, 4, 4, 137, 225) && Mixed(&image, 7, 4, 225, 137),
          "a linear gradient, repeated");
    CHECK(BoxIs(&scene, LINEAR_REFLECT, 0.0f, 1, 8, 8, 8, &image) &&
              Mixed(&image, 1, 4, 137, 225) && Mixed(&image, 4, 4, 137, 225) &&
              Mixed(&image, 7, 4, 225, 137),
          "a linear gradient, reflected");
    CHECK(BoxIs(&scene, LINEAR_UNORDERED, 0.0f, 1, 8, 8, 8, &image) &&
              Mixed(&image, 1, 4, 255, 0) && Mixed(&image, 4, 4, 137, 225),
          "stops in the font out of order");
    // Along the diagonal: pixels 6, 1 and 7, 2 alike, at 0.5; 2, 1 at 0.
    CHECK(BoxIs(&scene, LINEAR_TURNED, 0.0f, 1, 8, 8, 8, &image) && Mixed(&image, 6, 1, 188, 188) &&
              Mixed(&image, 7, 2, 188, 188) && Mixed(&image, 2, 1, 255, 0),
          "a linear gradient turned by its third point");
    // Out from 5, 4 to a radius of 4: pixel 5, 4 at 0.177, pixel 8, 4 at
    // 0.884, pixel 1, 0 past it.
    CHECK(BoxIs(&scene, RADIAL, 0.0f, 1, 8, 8, 8, &image) && Mixed(&image, 5, 4, 234, 117) &&
              Mixed(&image, 8, 4, 96, 242) && Mixed(&image, 1, 0, 0, 255),
          "a radial gradient");
    CHECK(BoxIs(&scene, RADIAL_TUBE, 0.0f, 1, 8, 8, 8, &image) && Mixed(&image, 4, 4, 155, 214) &&
              Is(&image, 4, 7, 0, 0, 0, 0),
          "a radial gradient, nothing outside its circles");
    // About 5, 4, counter-clockwise from the right: pixel 8, 4 at 8.1
    // degrees, 5, 7 at 81.9, 2, 4 at 168.7; 5, 1, at 281.3, padded.
    CHECK(BoxIs(&scene, SWEEP, 0.0f, 1, 8, 8, 8, &image) && Mixed(&image, 8, 4, 250, 60) &&
              Mixed(&image, 5, 7, 195, 180) && Mixed(&image, 2, 4, 71, 248) &&
              Mixed(&image, 5, 1, 0, 255),
          "a sweep gradient");
    // Pixel 6, 4 at (650, 450) units: t = c / 2b, 0.893.
    CHECK(BoxIs(&scene, RADIAL_TANGENT, 0.0f, 1, 8, 8, 8, &image) && Mixed(&image, 6, 4, 92, 243),
          "a radial gradient of circles touching inside");
    // Pixel 4, 4's centre taken back through the shear to 225 units:
    // 0.156 along.
    CHECK(BoxIs(&scene, LINEAR_SHEARED, 0.0f, 1, 8, 8, 8, &image) && Mixed(&image, 4, 4, 237, 110),
          "a linear gradient sheared");
    // Half a pixel right, pixel 4's centre is at 4 across: 0.5 along.
    CHECK(BoxIs(&scene, LINEAR_PAD, 0.5f, 1, 8, 9, 8, &image) && Mixed(&image, 4, 4, 188, 188),
          "a linear gradient at an offset pen");
    muiDestroyTextService(scene.service);
}

// At an em of 15.625 pixels a unit is a 64th of a pixel: pixel 6's
// centre, 416 units, falls exactly on the hard stop at 0.453125, where
// the later of its two stops colours it.
static void TestHardStop(void)
{
    Scene scene = MakeScene();
    const muiLinearColor green = {0.0f, 1.0f, 0.0f, 1.0f};
    muiGlyphImage image = {0};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, LINEAR_HARD, 15.625f, 0.0f, 0, green,
                              &image, s_pixels, sizeof s_pixels) == mui_success &&
              Mixed(&image, 5, 4, 255, 0) && Mixed(&image, 6, 4, 0, 255),
          "a hard stop, the later stop at its offset");
    muiDestroyTextService(scene.service);
}

static void TestComposite(void)
{
    Scene scene = MakeScene();
    muiGlyphImage image = {0};
    CHECK(BoxIs(&scene, COMPOSITED, 0.0f, 1, 8, 8, 8, &image) && Is(&image, 2, 4, 0, 255, 0, 255) &&
              Is(&image, 6, 4, 0, 0, 0, 0) && Is(&image, 8, 4, 0, 0, 0, 0),
          "a composite, its source out of its backdrop");
    muiDestroyTextService(scene.service);
}

// A graph that reaches one paint by many paths, within the depth bound,
// is refused once it has visited MUI_MAX_PAINT_VISITS paints, where it
// would otherwise take about two billion: its box walked, and, under a
// clip box, its paints.
static void TestBranched(void)
{
    Scene scene = MakeScene();
    const muiLinearColor ink = {0.2f, 0.4f, 0.8f, 0.75f};
    muiGlyphImage image = {0};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, BRANCHED, 10.0f, 0.0f, 0, ink, &image,
                              s_pixels, sizeof s_pixels) == mui_errorFormat,
          "a graph's box of too many paints refused");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, BOXED_BRANCHED, 10.0f, 0.0f, 0, ink,
                              &image, s_pixels, sizeof s_pixels) == mui_errorFormat,
          "a graph of too many paints refused");
    muiDestroyTextService(scene.service);
}

static void TestContract(void)
{
    Scene scene = MakeScene();
    const muiLinearColor green = {0.0f, 1.0f, 0.0f, 1.0f};
    muiGlyphImage image = {0};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                              NULL, 0) == mui_errorCapacity &&
              image.width == 8 && image.height == 8,
          "too few bytes, the size told");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, 8 * 8 * 4 - 1) == mui_errorCapacity &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                                  s_pixels, 8 * 8 * 4) == mui_success,
          "four bytes a pixel");
    CHECK(muiRenderColorGlyph(NULL, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image, s_pixels,
                              sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, NULL,
                                  s_pixels, sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                                  NULL, 4) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 0.0f, 0.0f, 0, green, &image,
                                  s_pixels, sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 1.0f, 0, green, &image,
                                  s_pixels, sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, 100, 10.0f, 0.0f, 0, green, &image,
                                  s_pixels, sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font + 1, GLYPH_A, 10.0f, 0.0f, 0, green,
                                  &image, s_pixels, sizeof s_pixels) == mui_errorStale,
          "outside the contract");
    muiDestroyTextService(scene.service);
}

static uint32_t Next(uint32_t* state)
{
    *state ^= *state << 13;
    *state ^= *state >> 17;
    *state ^= *state << 5;
    return *state;
}

static uint32_t Big32(const unsigned char* p)
{
    return (uint32_t)p[0] << 24 | (uint32_t)p[1] << 16 | (uint32_t)p[2] << 8 | p[3];
}

// Where a table lies in the font, from its directory; false for none.
static bool FindTable(const char tag[4], uint32_t* offset, uint32_t* length)
{
    uint32_t count = (uint32_t)s_color[4] << 8 | s_color[5];
    for (uint32_t i = 0; i < count && 12 + 16 * (size_t)(i + 1) <= sizeof s_color; i++)
    {
        const unsigned char* record = s_color + 12 + 16 * i;
        if (memcmp(record, tag, 4) == 0)
        {
            *offset = Big32(record + 8);
            *length = Big32(record + 12);
            return *length != 0 && *offset <= sizeof s_color && *length <= sizeof s_color - *offset;
        }
    }
    return false;
}

// Draws every glyph of a damaged font at two sizes; whether each was
// drawn or refused as the contract allows, a glyph past the font's count
// refused as invalid.
static bool DrawDamaged(muiTextService* service, uint64_t font, uint32_t glyphCount,
                        uint32_t* drawn)
{
    const muiLinearColor green = {0.0f, 1.0f, 0.0f, 1.0f};
    bool allowed = true;
    for (uint32_t glyph = 0; glyph <= COMPOSITED; glyph++)
    {
        for (int i = 0; i < 2; i++)
        {
            muiGlyphImage image = {0};
            muiResult result =
                muiRenderColorGlyph(service, font, glyph, i == 0 ? 10.0f : 40.0f, 0.25f, glyph % 2,
                                    green, &image, s_large, sizeof s_large);
            allowed = allowed &&
                      (result == mui_success || result == mui_empty || result == mui_errorFormat ||
                       (result == mui_errorInvalid && glyph >= glyphCount) ||
                       (result == mui_errorCapacity &&
                        (size_t)image.width * image.height * 4 > sizeof s_large));
            *drawn += result == mui_success && image.width != 0 ? 1 : 0;
        }
    }
    return allowed;
}

static void TestDamage(void)
{
    uint32_t colr = 0;
    uint32_t colrLength = 0;
    uint32_t cpal = 0;
    uint32_t cpalLength = 0;
    CHECK(FindTable("COLR", &colr, &colrLength) && FindTable("CPAL", &cpal, &cpalLength),
          "the font's COLR and CPAL");
    uint32_t state = 0x6C8E9CF5u;
    uint32_t made = 0;
    uint32_t drawn = 0;
    bool allowed = true;
    for (uint32_t round = 0; round < DAMAGE_ROUNDS && colrLength != 0 && cpalLength != 0; round++)
    {
        memcpy(s_damaged, s_color, sizeof s_color);
        for (uint32_t i = 0, flips = 1 + Next(&state) % 8; i < flips; i++)
        {
            uint32_t kind = Next(&state) % 4;
            uint32_t at = kind == 0   ? colr + Next(&state) % colrLength
                          : kind == 1 ? cpal + Next(&state) % cpalLength
                                      : Next(&state) % (uint32_t)sizeof s_damaged;
            s_damaged[at] ^= (unsigned char)(1u << (Next(&state) % 8));
        }
        muiTextServiceDef def = muiDefaultTextServiceDef();
        muiTextService* service = NULL;
        if (muiCreateTextService(&def, &service) != mui_success)
        {
            CHECK(false, "a text service");
            return;
        }
        muiFontDef fontDef = muiDefaultFontDef();
        fontDef.data = s_damaged;
        fontDef.size = sizeof s_damaged;
        fontDef.dataMode = mui_fontDataBorrow;
        muiFontId id = {0, 0};
        muiFontMetrics metrics = {0};
        if (muiCreateFont(service, &fontDef, &id) == mui_success &&
            muiFont_GetMetrics(service, id, &metrics) == mui_success)
        {
            made++;
            allowed =
                DrawDamaged(service, muiFont_GetKey(id), metrics.glyphCount, &drawn) && allowed;
        }
        muiDestroyTextService(service);
    }
    CHECK(allowed, "damaged glyphs drawn or refused as the contract allows");
    CHECK(made > DAMAGE_ROUNDS / 2 && drawn > made, "damaged fonts made and their glyphs drawn");
}

// A colour font with one palette, as most have: its colours are used
// (found by a mutant asking for two). A copy of Maul Color whose CPAL
// says one palette; the second's index after it is left, unread.
static void TestOnePalette(void)
{
    memcpy(s_onePalette, s_color, sizeof s_color);
    uint32_t tables = (uint32_t)s_color[4] << 8 | s_color[5];
    size_t cpal = 0;
    for (uint32_t i = 0; i < tables; i++)
    {
        const unsigned char* record = &s_color[12 + 16 * (size_t)i];
        if (memcmp(record, "CPAL", 4) == 0)
        {
            cpal = (size_t)record[8] << 24 | (size_t)record[9] << 16 | (size_t)record[10] << 8 |
                   record[11];
        }
    }
    CHECK(cpal != 0 && s_onePalette[cpal + 4] == 0 && s_onePalette[cpal + 5] == 2,
          "Maul Color's CPAL, two palettes");
    s_onePalette[cpal + 5] = 1;
    muiTextServiceDef def = muiDefaultTextServiceDef();
    muiTextService* service = NULL;
    CHECK(muiCreateTextService(&def, &service) == mui_success, "a text service");
    muiFontDef font = muiDefaultFontDef();
    font.data = s_onePalette;
    font.size = sizeof s_onePalette;
    font.dataMode = mui_fontDataBorrow;
    muiFontId id = {0, 0};
    CHECK(muiCreateFont(service, &font, &id) == mui_success, "one palette");
    const muiLinearColor green = {0.0f, 1.0f, 0.0f, 1.0f};
    muiGlyphImage image = {0};
    CHECK(muiRenderColorGlyph(service, muiFont_GetKey(id), GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              Is(&image, 1, 7, 255, 0, 0, 255) && Is(&image, 8, 0, 187, 0, 188, 255),
          "its palette's colours");
    CHECK(muiRenderColorGlyph(service, muiFont_GetKey(id), GLYPH_A, 10.0f, 0.0f, 1, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              Is(&image, 1, 7, 255, 0, 0, 255),
          "the second, past the font's, is the first");
    muiDestroyTextService(service);
}

// An image's bytes, four a pixel, as an FNV-1a hash.
static uint32_t Hash(const muiGlyphImage* image)
{
    uint32_t hash = 2166136261u;
    for (size_t i = 0; i < (size_t)image->width * image->height * 4; i++)
    {
        hash = (hash ^ s_pixels[i]) * 16777619u;
    }
    return hash;
}

// A rendering's result with its image: the hash, or the status for none.
static uint32_t Outcome(muiResult result, const muiGlyphImage* image)
{
    return result == mui_success ? Hash(image) : (uint32_t)result;
}

// Every colour glyph the font has, whole: layers in both palettes, at
// fractional sizes and pens, and each version 1 paint graph at two
// sizes; the same bytes on every platform (record mui-0001).
static void TestWholeImages(void)
{
    static const uint32_t expected[52] = {
        0x2fed08adu, 0x833ebec5u, 0xeb5adc49u, 0xc1250710u, 0x382aa79fu, 0x78aa4bd1u, 0xb946cfb4u,
        0x22fde81du, 0xc283f329u, 0xcd2fb1c5u, 0x1b94ae85u, 0xa2767263u, 0x27eef589u, 0x4f10afefu,
        0xb7c33b52u, 0xcf292541u, 0xe81bb10du, 0x88e09b2du, 0xcf90dfe4u, 0x3d6d9149u, 0xfffffffcu,
        0xfffffffcu, 0xfffffffcu, 0xfffffffcu, 0x0e132485u, 0x37eb84abu, 0xfffffffcu, 0xfffffffcu,
        0x49391f5du, 0x1616abb5u, 0xa4694479u, 0x8e5e632du, 0xb2ed311du, 0xf9cb89cdu, 0xd469375au,
        0x3b83c7a5u, 0xdac84861u, 0x9084a53du, 0x5e60b5cdu, 0x9df109fdu, 0x21d8da2cu, 0xd5b27da9u,
        0x49391f5du, 0x1616abb5u, 0xb308f82fu, 0xcc829421u, 0x55280b9eu, 0xc83af64au, 0xc0187ec5u,
        0xd64992a5u, 0x316fa0f9u, 0x3a5908f5u};
    Scene scene = MakeScene();
    const muiLinearColor ink = {0.2f, 0.4f, 0.8f, 0.75f};
    const struct
    {
        float size;
        float offset;
        uint32_t palette;
    } layers[4] = {{10.0f, 0.0f, 0}, {13.5f, 0.25f, 0}, {10.0f, 0.5f, 1}, {33.0f, 0.75f, 1}};
    uint32_t got[52];
    uint32_t n = 0;
    for (uint32_t k = 0; k < 4; k++)
    {
        muiGlyphImage image = {0};
        muiResult result = muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, layers[k].size,
                                               layers[k].offset, layers[k].palette, ink, &image,
                                               s_pixels, sizeof s_pixels);
        got[n++] = Outcome(result, &image);
    }
    for (uint32_t glyph = LAYERED; glyph <= COMPOSITED; glyph++)
    {
        for (uint32_t k = 0; k < 2; k++)
        {
            muiGlyphImage image = {0};
            muiResult result = muiRenderColorGlyph(scene.service, scene.font, glyph,
                                                   k == 0 ? 16.0f : 27.5f, k == 0 ? 0.0f : 0.25f, 0,
                                                   ink, &image, s_pixels, sizeof s_pixels);
            got[n++] = Outcome(result, &image);
        }
    }
    bool held = n == 52;
    for (uint32_t i = 0; i < n; i++)
    {
        held = held && got[i] == expected[i];
    }
    CHECK(held, "every colour glyph's bytes, as on every platform");
    muiDestroyTextService(scene.service);
}

int main(void)
{
    TestLayers();
    TestWholeImages();
    TestOnePalette();
    TestPaints();
    TestGradients();
    TestHardStop();
    TestComposite();
    TestBranched();
    TestContract();
    TestDamage();
    return s_failures == 0 ? 0 : 1;
}
