// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Sirac Ozmen
//
// Colour glyphs from MaulColor.ttf (generated by make_color_font.py): its
// A, at an em of 10 pixels, is a layer with no outline, a box from 1 to 9
// across and 0 to 8 up of palette entry 0, its right half (5 to 9) of
// entry 1 over it, a box from 3 to 5 across and 2 to 4 up of the text's
// colour, and a box from 6 to 8 across and 2 to 4 up of entry 2, past
// the palettes' two; palette 0 is opaque red and half transparent blue,
// palette 1 green and yellow. Its B has no colour layers. Glyphs 9 on are
// version 1 paint graphs, one for each kind of paint, described in the
// font's script.

#include "test_harness.h"

#include "maul-ui/font.h"
#include "maul-ui/glyph_image.h"
#include "maul-ui/text_block.h"

#include <string.h>

#include "color.inc"

enum
{
    GLYPH_A = 1,
    GLYPH_B = 2,
    LAYERED = 9,
    MOVED,
    TURNED,
    SCALED,
    SKEWED,
    TRANSFORMED,
    REUSED,
    CLIPPED,
    LOOPED,
    FLATTENED
};

static unsigned char s_pixels[4096];

typedef struct Scene
{
    muiTextService* service;
    uint64_t font;
} Scene;

static Scene MakeScene(void)
{
    Scene scene = {0};
    muiTextServiceDef def = muiDefaultTextServiceDef();
    CHECK(muiCreateTextService(&def, &scene.service) == mui_success, "a text service");
    muiFontDef font = muiDefaultFontDef();
    font.data = s_color;
    font.size = sizeof s_color;
    font.dataMode = mui_fontDataBorrow;
    muiFontId id = {0, 0};
    CHECK(muiCreateFont(scene.service, &font, &id) == mui_success, "Maul Color");
    scene.font = muiFont_GetKey(id);
    return scene;
}

// Whether the pixel at x, y (y up, from the image's place) is these bytes.
static bool Is(const muiGlyphImage* image, int32_t x, int32_t y, int r, int g, int b, int a)
{
    uint32_t column = (uint32_t)(x - image->left);
    uint32_t row = (uint32_t)(image->top - 1 - y);
    const unsigned char* p = &s_pixels[((size_t)row * image->width + column) * 4];
    return p[0] == r && p[1] == g && p[2] == b && p[3] == a;
}

static void TestLayers(void)
{
    Scene scene = MakeScene();
    const muiLinearColor green = {0.0f, 1.0f, 0.0f, 1.0f};
    muiGlyphImage image = {0};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              image.left == 1 && image.top == 8 && image.width == 8 && image.height == 8,
          "the layers' joint box");
    // Blue at alpha 128 over red: linear 0.498 red and 0.502 blue, 187
    // and 188 encoded.
    CHECK(Is(&image, 1, 7, 255, 0, 0, 255) && Is(&image, 4, 0, 255, 0, 0, 255), "palette entry 0");
    CHECK(Is(&image, 5, 7, 187, 0, 188, 255) && Is(&image, 8, 0, 187, 0, 188, 255),
          "entry 1, half transparent, over it");
    CHECK(Is(&image, 7, 3, 187, 0, 188, 255), "an entry past the palette, transparent");
    CHECK(Is(&image, 3, 2, 0, 255, 0, 255) && Is(&image, 4, 3, 0, 255, 0, 255) &&
              Is(&image, 2, 2, 255, 0, 0, 255),
          "the text's colour");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 1, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              Is(&image, 1, 7, 0, 255, 0, 255) && Is(&image, 8, 0, 255, 255, 0, 255),
          "the second palette");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 7, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              Is(&image, 1, 7, 255, 0, 0, 255),
          "a palette past the font's, the first");
    const muiLinearColor clear = {0.0f, 0.0f, 0.0f, 0.0f};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, clear, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              Is(&image, 3, 2, 255, 0, 0, 255),
          "a clear text colour shows what is under it");
    // Half a pixel right: the joint box widens by one, its first column
    // half covered by red.
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.5f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              image.left == 1 && image.width == 9 && Is(&image, 1, 7, 188, 0, 0, 128),
          "an offset pen");
    unsigned char first[9 * 8 * 4];
    memcpy(first, s_pixels, sizeof first);
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.5f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              memcmp(first, s_pixels, sizeof first) == 0,
          "rendered again, the same");
    image = (muiGlyphImage){5, 5, 5, 5};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_B, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_empty &&
              image.width == 0 && image.height == 0,
          "a glyph without colour is empty");
    muiDestroyTextService(scene.service);
}

// Whether a glyph renders at an em of 10 and a pen offset into this box,
// left and top, width and height, in palette 0 and green text.
static bool BoxIs(Scene* scene, uint32_t glyph, float offset, int32_t left, int32_t top,
                  uint32_t width, uint32_t height, muiGlyphImage* image)
{
    const muiLinearColor green = {0.0f, 1.0f, 0.0f, 1.0f};
    return muiRenderColorGlyph(scene->service, scene->font, glyph, 10.0f, offset, 0, green, image,
                               s_pixels, sizeof s_pixels) == mui_success &&
           image->left == left && image->top == top && image->width == width &&
           image->height == height;
}

static void TestPaints(void)
{
    Scene scene = MakeScene();
    muiGlyphImage image = {0};
    // The text's colour at half alpha over red: linear half red and half
    // green, 188 encoded.
    CHECK(BoxIs(&scene, LAYERED, 0.0f, 1, 8, 8, 8, &image) && Is(&image, 1, 7, 255, 0, 0, 255) &&
              Is(&image, 3, 2, 188, 188, 0, 255) && Is(&image, 5, 2, 255, 0, 0, 255),
          "layers, a solid's alpha and the text's colour");
    const muiLinearColor green = {0.0f, 1.0f, 0.0f, 1.0f};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, LAYERED, 10.0f, 0.0f, 1, green, &image,
                              s_pixels, sizeof s_pixels) == mui_success &&
              Is(&image, 1, 7, 0, 255, 0, 255),
          "a graph in the second palette");
    CHECK(BoxIs(&scene, MOVED, 0.0f, 6, 5, 2, 2, &image) && Is(&image, 6, 3, 255, 0, 0, 255) &&
              Is(&image, 7, 4, 255, 0, 0, 255),
          "a translation");
    CHECK(BoxIs(&scene, MOVED, 0.5f, 6, 5, 3, 2, &image) && Is(&image, 6, 3, 188, 0, 0, 128) &&
              Is(&image, 7, 3, 255, 0, 0, 255),
          "a translation at an offset pen");
    CHECK(BoxIs(&scene, TURNED, 0.0f, 2, 6, 1, 4, &image) && Is(&image, 2, 5, 255, 0, 0, 255),
          "a rotation counter-clockwise about a centre");
    CHECK(BoxIs(&scene, SCALED, 0.0f, 3, 3, 3, 1, &image) && Is(&image, 5, 2, 255, 0, 0, 255),
          "a scale about a centre");
    // At 3 to 4 up, the skewed dot spans 2 to 1 on its left and 4 to 3 on
    // its right: pixel 2, 3 is whole, pixel 4, 3 untouched.
    CHECK(BoxIs(&scene, SKEWED, 0.0f, 1, 4, 4, 2, &image) && Is(&image, 2, 3, 255, 0, 0, 255) &&
              Is(&image, 4, 3, 0, 0, 0, 0),
          "a skew, its top leaning left");
    CHECK(BoxIs(&scene, TRANSFORMED, 0.0f, 3, 4, 4, 2, &image) &&
              Is(&image, 5, 3, 255, 0, 0, 255) && Is(&image, 3, 3, 0, 0, 0, 0),
          "an affine transform");
    CHECK(BoxIs(&scene, REUSED, 0.0f, 3, 5, 2, 2, &image) && Is(&image, 3, 3, 255, 0, 0, 255),
          "another colour glyph's graph, transformed");
    CHECK(BoxIs(&scene, CLIPPED, 0.0f, 3, 4, 2, 2, &image) && Is(&image, 3, 2, 255, 0, 0, 255) &&
              Is(&image, 4, 3, 255, 0, 0, 255),
          "a clip box");
    CHECK(BoxIs(&scene, CLIPPED, 0.5f, 3, 4, 3, 2, &image) && Is(&image, 3, 2, 188, 0, 0, 128) &&
              Is(&image, 4, 2, 255, 0, 0, 255) && Is(&image, 5, 3, 188, 0, 0, 128),
          "nothing outside the clip box, at an offset pen");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, LOOPED, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_errorFormat,
          "a graph that paints itself");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, FLATTENED, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, sizeof s_pixels) == mui_errorFormat,
          "a skew of a quarter turn, its outline without end");
    muiDestroyTextService(scene.service);
}

static void TestContract(void)
{
    Scene scene = MakeScene();
    const muiLinearColor green = {0.0f, 1.0f, 0.0f, 1.0f};
    muiGlyphImage image = {0};
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                              NULL, 0) == mui_errorCapacity &&
              image.width == 8 && image.height == 8,
          "too few bytes, the size told");
    CHECK(muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                              s_pixels, 8 * 8 * 4 - 1) == mui_errorCapacity &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                                  s_pixels, 8 * 8 * 4) == mui_success,
          "four bytes a pixel");
    CHECK(muiRenderColorGlyph(NULL, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image, s_pixels,
                              sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, NULL,
                                  s_pixels, sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 0.0f, 0, green, &image,
                                  NULL, 4) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 0.0f, 0.0f, 0, green, &image,
                                  s_pixels, sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, GLYPH_A, 10.0f, 1.0f, 0, green, &image,
                                  s_pixels, sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font, 100, 10.0f, 0.0f, 0, green, &image,
                                  s_pixels, sizeof s_pixels) == mui_errorInvalid &&
              muiRenderColorGlyph(scene.service, scene.font + 1, GLYPH_A, 10.0f, 0.0f, 0, green,
                                  &image, s_pixels, sizeof s_pixels) == mui_errorStale,
          "outside the contract");
    muiDestroyTextService(scene.service);
}

int main(void)
{
    TestLayers();
    TestPaints();
    TestContract();
    return s_failures == 0 ? 0 : 1;
}
