#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Sirac Ozmen
#
# Builds the reference renderer's shader container (record mui-0005)
# offline, as Maul RHI's own script does: glslangValidator compiles each stage of
# rhi/shaders/quad.* under its entry name, spirv-link joins them, spirv-val
# checks the module for Vulkan 1.3, and Maul RHI's tools cross it to
# DXIL (spirv-cross and dxc) and Metal (spirv-cross) and write the
# container with the WGSL beside it, which lands in
# rhi/shaders/quad_container.h as bytes. CI runs none of these tools; the
# header is committed, and this script is run again whenever a source
# changes.
#
# usage: gen_rhi_shaders.py <a Maul RHI source tree, for its tools/>

import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADERS = os.path.join(ROOT, "rhi", "shaders")
NAME = "quad"
STAGES = (("vert", "vs"), ("frag", "fs"))


def run(*command):
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"{command[0]} failed:\n{result.stdout}{result.stderr}")


def build(work, tools):
    modules = []
    for suffix, entry in STAGES:
        module = os.path.join(work, f"{NAME}_{entry}.spv")
        run("glslangValidator", "-V", "--target-env", "vulkan1.3", "-e", entry,
            "--source-entrypoint", "main", "-o", module,
            os.path.join(SHADERS, f"{NAME}.{suffix}"))
        modules.append(module)
    linked = os.path.join(work, f"{NAME}.spv")
    run("spirv-link", "--target-env", "vulkan1.3", *modules, "-o", linked)
    run("spirv-val", "--target-env", "vulkan1.3", linked)
    reflection = os.path.join(SHADERS, f"{NAME}.json")
    dxil = os.path.join(work, "dxil")
    msl = os.path.join(work, "msl")
    run(sys.executable, os.path.join(tools, "mrhi_dxil.py"), linked, reflection, dxil)
    run(sys.executable, os.path.join(tools, "mrhi_msl.py"), linked, reflection, msl)
    container = os.path.join(work, f"{NAME}.mrsc")
    run(sys.executable, os.path.join(tools, "mrhi_container.py"), "--dxil", dxil, "--msl", msl,
        linked, os.path.join(SHADERS, f"{NAME}.wgsl"), reflection, container)
    with open(container, "rb") as file:
        return file.read()


def header(data):
    guard = f"MAUL_UI_{NAME.upper()}_CONTAINER_H"
    lines = [
        "// SPDX-License-Identifier: MIT",
        "// Copyright (c) 2026 Sirac Ozmen",
        "//",
        "// The reference renderer's shader container, generated by",
        f"// tools/gen_rhi_shaders.py from rhi/shaders/{NAME}.*: edit the sources",
        "// and run the script, not this file.",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdalign.h>",
        "#include <stdint.h>",
        "",
        f"alignas(8) static const uint8_t s_{NAME}Container[{len(data)}] = {{",
    ]
    for at in range(0, len(data), 16):
        lines.append("    " + " ".join(f"0x{b:02X}," for b in data[at:at + 16]))
    lines += ["};", "", f"#endif // {guard}", ""]
    return "\n".join(lines)


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: gen_rhi_shaders.py <a Maul RHI source tree>")
    tools = os.path.join(os.path.abspath(sys.argv[1]), "tools")
    with tempfile.TemporaryDirectory() as work:
        data = build(work, tools)
    path = os.path.join(SHADERS, f"{NAME}_container.h")
    with open(path, "w", encoding="utf-8", newline="\n") as file:
        file.write(header(data))
    print(f"{os.path.relpath(path, ROOT)}: {len(data)} bytes")


if __name__ == "__main__":
    main()
